language: php

env:
  global:
    - secure: "y9agp+2OifHS1Ao8PjSBGzIuaUFp4ynskPCAXCgtyn6pjgGt1BDvT0dVTKE2JOhEoSywp1PMM4/oCwJxR+mIvJrCRBaC0BTew3VMc0qk51r+0RK3+lAAkZdU2KQaQT55/riSOhQ08RkBy2336HXogPFnbV1B0wfWRDGNBS5JNxBpX5ot3+RNeRv+ydBYBabrjo3N/bULh8lWVVmrXrJfP9mtwDA74veMfTiVahBuz/HSRugsITQyZ6+q5p0neVNIkL9WQiO4sCr1zaM3JoD0moAUIuWlSjYrsUsE2gycYSohAX/3NkpGVD1N249/MB/hnBorjYcjyx+3QkeWSzsHirKE/WPyJGj37jX5JdS3I1dZeKvDncQPUOqVZFbTsJ2UNPtnIzZJYTRzC4YQaBxLGY3ZBJvbYlsrqd66hMC6rDgJ9kjTVdf7gANWa4MGOki3E+JUZo4k1KyLW4kueUJ45rKj+olg4ZNNPswwRXdU7iOOG89xDICS/anOzYChqpY/i15ftzpdWW8bNcnw4h4YHDUynRINoxEFOW4p7zpRN0fDuz2/3poY/fb+sq8i5bL2G0JlZDntStgMgPRZfew3KazO6L93WkuvHlbgdV9ovp1xWE5YafuccHM7tYLgEMgxslPtkhnQ57MFzktt6JE6iFoR6W/ZiNjNxhhod1w5Vlg="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.phpstan
    - $HOME/.phpunit

stages:
  - style
  - stan
  - test
  - infection

jobs:
  include:
    - stage: Style

      php: 7.1

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p $HOME/.php-cs-fixer

      script:
        - composer normalize --dry-run
        - vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --verbose

    - stage: Stan

      php: 7.2

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p $HOME/.phpstan

      script:
        - vendor/bin/phpstan analyse --configuration=phpstan.neon src test

    - &TEST

      stage: Test

      php: 7.1

      env: WITH_LOWEST=true

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; fi
        - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
        - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

      script:
        - vendor/bin/phpunit --configuration=test/AutoReview/phpunit.xml
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi

    - <<: *TEST

      php: 7.1

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.1

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOWEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOCKED=true WITH_COVERAGE=true

    - <<: *TEST

      php: 7.2

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.3

      env: WITH_LOWEST=true

    - <<: *TEST

      php: 7.3

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.3

      env: WITH_HIGHEST=true

    - stage: Infection

      php: 7.2

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - xdebug-enable
        - mkdir -p $HOME/.infection

      script:
        - vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100

notifications:
  email: false
